#!/usr/bin/env bash
# sync-sources.sh -- Clone/pull all app source repos to /opt/app-sources/
# Generates paths.env for docker compose to use.
#
# Usage: ./scripts/sync-sources.sh [sources_dir]
#
# On a dev Mac, you don't need this -- just create paths.env manually
# pointing to your local CTOWorkspace dirs.
#
# On the server, this script:
#   1. Reads registry.yaml for app source repos
#   2. Clones or pulls each repo
#   3. Writes paths.env with resolved paths

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SOURCES_DIR="${1:-/opt/app-sources}"
PATHS_ENV="$PROJECT_DIR/paths.env"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[sync]${NC} $*"; }
warn() { echo -e "${YELLOW}[sync]${NC} $*"; }
err()  { echo -e "${RED}[sync]${NC} $*" >&2; }

# Ensure sources directory exists
mkdir -p "$SOURCES_DIR"

# Parse registry.yaml for app sources
# Uses simple grep/awk since we can't assume yq is installed
log "Syncing app sources to $SOURCES_DIR..."

# Map of app-id -> (repo, path, env_var)
# Format: ENV_VAR|repo|subpath
APPS=(
    "TICKETMAKER_PATH|rtkshmclane/CTOWorkspace|02_R_and_D/ticketmaker"
    "DETECTION_CATALOG_PATH|rtkshmclane/CTOWorkspace|02_R_and_D/detection_catalog"
    "INTEGRATION_ADOPTION_PATH|rtkshmclane/CTOWorkspace|03_Product/integration_adoption/analytics"
    "INTEGRATION_CATALOG_PATH|rtkshmclane/CTOWorkspace|03_Product/integration_catalog/dashboard"
    "CLOUD_LIVE_PATH|rtkshmclane/CTOWorkspace|02_R_and_D/AW_Point_Products_Demo/aw_managed_cloud_live"
    "NETWORK_GRAPH_PATH|rtkshmclane/CTOWorkspace|02_R_and_D/network_graph_playground"
    "ANALYTIC_STORIES_PATH|rtkshmclane/CTOWorkspace|Collaborators/BradB/idr/detection_coe/poc/analytic_stories"
)

# Track which repos we've already cloned/pulled
declare -A CLONED_REPOS

# Start fresh paths.env
echo "# Auto-generated by sync-sources.sh -- $(date)" > "$PATHS_ENV"
echo "# Do not edit manually. Re-run sync-sources.sh to regenerate." >> "$PATHS_ENV"
echo "" >> "$PATHS_ENV"

for entry in "${APPS[@]}"; do
    IFS='|' read -r ENV_VAR REPO SUBPATH <<< "$entry"
    REPO_NAME=$(basename "$REPO")
    REPO_DIR="$SOURCES_DIR/$REPO_NAME"

    # Clone or pull the repo (only once per repo)
    if [ -z "${CLONED_REPOS[$REPO_NAME]+x}" ]; then
        if [ -d "$REPO_DIR/.git" ]; then
            log "Pulling $REPO..."
            (cd "$REPO_DIR" && git pull --ff-only 2>&1) || warn "Pull failed for $REPO -- using existing"
        else
            log "Cloning $REPO..."
            git clone "https://github.com/${REPO}.git" "$REPO_DIR" 2>&1 || {
                err "Failed to clone $REPO"
                continue
            }
        fi
        CLONED_REPOS[$REPO_NAME]=1
    fi

    # Resolve the full path
    FULL_PATH="$REPO_DIR/$SUBPATH"
    if [ -d "$FULL_PATH" ]; then
        echo "${ENV_VAR}=${FULL_PATH}" >> "$PATHS_ENV"
        log "  $ENV_VAR -> $FULL_PATH"
    else
        warn "  $ENV_VAR: path not found: $FULL_PATH"
        echo "# ${ENV_VAR}=${FULL_PATH}  # NOT FOUND" >> "$PATHS_ENV"
    fi
done

echo ""
log "paths.env written to $PATHS_ENV"
log "Done. Run 'source paths.env && docker compose up --build -d' to deploy."
